In [2]:
import numpy as np

## Numpy Array

##### Numpy's array core functionalities come from its ndarray object, a multidimensional array of elements. The difference between numpy array and a Python list is a Python list can hold multiple of data. Still, nnumpy arrays are homogeneous, which means it can hold single or same type data/elements. 

In [3]:
#cleating a basic numpy array

arr = np.array([1,2,3])
arr

array([1, 2, 3])

type(arr)

In [13]:
# Creating array for functions. To create a zeros,ones,linspace array you need to declare the row and column size using the .zeros(), ones(),linspace() function
arr_zero = np.zeros((3,3))
arr_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr_ones = np.ones((3,3)) # (3,3)=> Shape of the array
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
arr_space = np.linspace(0,10,5) #(0,10,5)=> starts from 0 and end on 10 elements have 5 difference between)
arr_space

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Array Attribute 

#### array attributes are used to get information from arrays. These are extremely helpful when we use them.

In [26]:
#Shape => get the shape of the array 
arr = np.array([1,2,3,5,6])
arr.shape
arr.size
arr.dtype
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [5],
       [6]])

## Indexing & Slicing

In [28]:
arr[2] # array indexing starts from 0 and [one element] is for 1D array

3

In [32]:
arr_2d = np.array([[2,3,5],[4,3,1],[9,8,0]])
arr_2d

array([[2, 3, 5],
       [4, 3, 1],
       [9, 8, 0]])

In [33]:
arr_2d.ndim

2

In [34]:
arr_2d[1,2] #This worked like a metrix

1

In [35]:
 arr[0:2] # Slicing an array

array([1, 2])

### Broadcasting
#### Broadcasting allows Numpy to perform element-wise operation on arrays of different shapes and size. Numpy automatically expands array's dimensions to make them compatible for operations

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [4]:
arr + 1 #adds 1 to each element in the array

array([[2, 3, 4],
       [5, 6, 7]])

### Mathematical Operations 

In [15]:
#Element Wise 
arr1 = np.array([[1,2,3],[3,4,5]])
arr1.shape

(2, 3)

In [6]:
arr + arr1 

array([[ 2,  4,  6],
       [ 7,  9, 11]])

In [11]:
ele_mult= arr * arr1
ele_mult

array([[ 1,  4,  9],
       [12, 20, 30]])

In [17]:
dot_mult = np.dot(arr, arr1.T)

In [18]:
dot_mult

array([[14, 26],
       [32, 62]])

In [19]:
arr.sum()

21

In [20]:
arr.mean()

3.5

In [21]:
# np.std
arr.std()

1.707825127659933

In [22]:
arr.min()

1

In [23]:
arr.max()

6

In [24]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])